#!/bin/bash
# 快速启动指南

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║          🎮 Pygame渲染已恢复 - 快速启动指南                    ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ OpenGL错误已修复"
echo "✅ Pygame渲染功能已恢复"
echo "✅ 所有测试通过"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 使用方法："
echo ""
echo "  方法1（推荐）- 使用启动脚本："
echo "    $ ./run_training_with_display.sh"
echo ""
echo "  方法2 - 一行命令："
echo "    $ LIBGL_ALWAYS_SOFTWARE=1 SDL_VIDEODRIVER=dummy python train_ppo_with_wandb.py"
echo ""
echo "  方法3 - 手动设置环境变量："
echo "    $ export LIBGL_ALWAYS_SOFTWARE=1"
echo "    $ export SDL_VIDEODRIVER=dummy"
echo "    $ python train_ppo_with_wandb.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 测试pygame功能："
echo "    $ python test_pygame_rendering.py"
echo ""
echo "📖 查看完整文档："
echo "    $ cat README_PYGAME_RENDERING.md"
echo "    $ cat PYGAME_FIX_SUMMARY.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚙️  当前配置："
echo "    - Pygame渲染: ✅ 已启用 (config.render = True)"
echo "    - 软件渲染: ✅ 已配置 (LIBGL_ALWAYS_SOFTWARE=1)"
echo "    - 虚拟显示: ✅ 已配置 (SDL_VIDEODRIVER=dummy)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 提示："
echo "    - 如需禁用渲染提高速度，修改 train_ppo_with_wandb.py 第777行"
echo "    - 训练日志保存在: training_log.json"
echo "    - 模型保存在: weights/ppo-carla-obs30/"
echo ""
echo "🚀 现在可以开始训练了！"
echo ""
