#!/bin/bash
# Overtaking 能力测试 - 快速参考卡

echo "========================================================================"
echo "🚗 Overtaking 能力测试 - 快速参考"
echo "========================================================================"
echo ""
echo "📍 位置: /home/ajifang/b2drive/overtaking/"
echo ""
echo "✅ 已创建的文件:"
echo ""
echo "📂 数据文件:"
echo "   ✅ data/overtaking.xml (196KB) - 45条Overtaking路线"
echo "   ✅ data/overtaking_route_ids.txt - 路线ID列表"
echo ""
echo "🔧 脚本文件:"
echo "   ✅ scripts/extract_overtaking_routes.py - 路线提取"
echo "   ✅ scripts/test_overtaking.sh - 测试执行"
echo "   ✅ scripts/analyze_results.py - 结果分析"
echo "   ✅ run.sh - 快速启动（交互式）"
echo ""
echo "📖 文档文件:"
echo "   ✅ README.md (11KB) - 详细使用指南"
echo "   ✅ SUMMARY.md (9.7KB) - 完整清单"
echo ""
echo "🎯 测试内容:"
echo "   - 9种Overtaking场景"
echo "   - 45条测试路线"
echo "   - 预计时间: 6-8小时"
echo ""
echo "🚀 快速启动（3种方法）:"
echo ""
echo "方法1 - 交互式菜单（推荐）:"
echo "   cd /home/ajifang/b2drive/overtaking"
echo "   ./run.sh"
echo ""
echo "方法2 - 直接运行测试:"
echo "   cd /home/ajifang/b2drive/overtaking"
echo "   screen -S overtaking_test"
echo "   ./scripts/test_overtaking.sh"
echo "   # 按 Ctrl+A, D 分离"
echo ""
echo "方法3 - 查看帮助:"
echo "   cd /home/ajifang/b2drive/overtaking"
echo "   cat README.md"
echo ""
echo "📊 监控进度:"
echo "   查看批次数: ls results/batches/*.json | wc -l"
echo "   实时监控:   watch -n 10 'ls results/batches/*.json 2>/dev/null | wc -l'"
echo "   CARLA日志:  tail -f /tmp/carla_overtaking.log"
echo ""
echo "📈 分析结果:"
echo "   cd /home/ajifang/b2drive/overtaking"
echo "   python3 scripts/analyze_results.py"
echo ""
echo "🎯 9种场景类型:"
echo "   1. Accident (事故场景) - 5条"
echo "   2. AccidentTwoWays (双向道路事故) - 5条"
echo "   3. ConstructionObstacle (施工障碍) - 5条"
echo "   4. ConstructionObstacleTwoWays (双向道路施工) - 5条"
echo "   5. HazardAtSideLane (侧方危险) - 5条"
echo "   6. HazardAtSideLaneTwoWays (双向道路侧方危险) - 5条"
echo "   7. ParkedObstacle (停车障碍) - 5条"
echo "   8. ParkedObstacleTwoWays (双向道路停车障碍) - 5条"
echo "   9. VehicleOpensDoorTwoWays (双向道路开车门) - 5条"
echo ""
echo "⚙️  配置参数:"
echo "   BATCH_SIZE=5 (每批5条路线)"
echo "   总批次数=9"
echo "   CARLA端口=2000"
echo "   TM端口=8000"
echo ""
echo "📁 输出文件:"
echo "   results/batches/batch_0.json ... batch_8.json"
echo "   results/overtaking_results.json (合并结果)"
echo "   results/overtaking_analysis.json (分析报告)"
echo ""
echo "🛠️  故障处理:"
echo "   清理CARLA: pkill -9 -f CarlaUE4"
echo "   清理端口:  for pid in \$(lsof -t -i:2000); do kill -9 \$pid; done"
echo "   断点续传:  脚本自动支持，直接重新运行即可"
echo ""
echo "========================================================================"
